name: 71Ess
main: aa.plugin.main.Main
version: 1.0.0
commands:
    gm:
        description: Change gamemode with GUI!!
    weather:
        description: Change weather with GUI!!
    spawn:
        description: spawn and setspawn !!
    time:
        description: set time with GUI!!
    tp:
        description: teleport to a player with GUI!!