name: 71Ess
main: aa.plugin.main.Main
version: 1.0.0
commands:
    gm:
        description: Change gamemode with GUI!!
    gamemode:
        description: Change gamemode with GUI!!
    weather:
        description: Change weather with GUI!!
    spawn:
        description: spawn and setspawn !!
    time:
        description: set time with GUI!!
    tp:
        description: teleport to a player with GUI!!
    tpc:
        description: teleport to coordinate
    home:
        description: home
    fly:
        description: heyhey redheart FLY!!
    god:
        description: change mode to god
    ping:
        description: get player's ping
    tpa:
        description: sent a invite of teleport require to player 
    msg:
        description: send a private message to a player
    msgr:
        description: resend a private message to a player
    tpall:
        description: teleport all player to sender
    signedit:
        description: edit your fucking signs!
    heal:
        description: heal your body
    afk:
        description: afk mode