name: 71Ess
main: aa.plugin.main.Main
version: 1.0.0
author: 7roub1e
commands:
    gm:
        description: Change gamemode with GUI!!
    gamemode:
        description: Change gamemode with GUI!!
    weather:
        description: Change weather with GUI!!
    spawn:
        description: spawn and setspawn !!
    time:
        description: set time with GUI!!
    tp:
        description: teleport to a player with GUI!!
    tpc:
        description: teleport to coordinate
    fly:
        description: heyhey redheart FLY!!
    god:
        description: change mode to god
    ping:
        description: get player's ping
    tpa:
        description: sent a invite of teleport require to player 
    tphere:
        description: sent a invite of teleport require to player 
    msg:
        description: send a private message to a player
    msgr:
        description: resend a private message to a player
    tpall:
        description: teleport all player to sender
    signedit:
        description: edit your fucking signs!
    heal:
        description: heal your body
    afk:
        description: afk mode
    back:
        description: back your lastone point
    broadcast:
        description: bc
    bc:
        description: bc
    chat:
        description: chat
    money:
        description: moneySystem
    home:
        description: home
permissions:
    71ess.afk:
        description: afk
        default: op
    71ess.back:
        description: back
        default: op
    71ess.broadcast:
        description: broadcast
        default: op
    71ess.chat:
        description: chatmanager
        default: op
    71ess.fly:
        description: fly
        default: op
    71ess.gamemode:
        description: gamemode
        default: op
    71ess.god:
        description: god
        default: op
    71ess.heal:
        description: heal
        default: op
    71ess.money:
        description: moneysystem
        default: op
    71ess.money.*:
        description: moneysystem
        default: op
        children:
            71ess.money.show: true
            71ess.money.give: true
            71ess.money.set: true
    71ess.home:
        description: home
        default: op
    71ess.home.*:
        description: home
        default: op
        children:
            71ess.home.set: true
            71ess.money.del: true
    71ess.home.set:
        description: sethome
        default: op
    71ess.home.del:
        description: delhome
        default: op
    71ess.money.show:
        description: show money
        default: op
    71ess.money.give:
        description: give money
        default: op
    71ess.money.set:
        description: setmoney
        default: op
    71ess.privatemessage:
        description: privatemessage
        default: op
    71ess.signedit:
        description: signedit
        default: op
    71ess.setspawn:
        description: setspawn
        default: op
    71ess.teleport:
        description: teleport
        default: op
    71ess.time:
        description: time
        default: op
    71ess.tpa:
        description: tpa
        default: op
    71ess.tahere:
        description: tphere
        default: op
    71ess.tpall:
        description: tpall
        default: op
    71ess.tardeChannel:
        description: tradeChannel
        default: op
    71ess.weather:
        description: weather
        default: op